name: CD To Staging on Develop
on: 
  push:
    branches: 
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Staging
      uses: appleboy/ssh-action@master
      env:
        USERNAME: ${{ secrets.SSH_USER }}
        HOST: ${{ secrets.SSH_HOST }}
        KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}
      with:
        script: |
          rm -r sentence.me
          git clone https://github.com/TheLacrox/sentence.me.git
          cd sentence.me 
          git checkout develop 
          git pull;
          sudo make build;
          sudo make dev;
          sudo make run;
